Dataset: Consider the following dataset of sales records:
Order ID Customer Product Category Quantity Price Total Sales
1001 Alice Laptop Electronics 2 800 1600
1002 Bob Phone Electronics 1 500 500
1003 Charlie Chair Furniture 4 100 400
1004 Alice Table Furniture 1 250 250
1005 David Laptop Electronics 1 800 800
1006 Charlie Phone Electronics 2 500 1000
1007 Bob Chair Furniture 2 100 200
1008 Alice Phone Electronics 1 500 500

In [1]:
import pandas as pd

In [2]:
# 1. Create DataFrame
data = {
    "Order ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Customer": ["Alice", "Bob", "Charlie", "Alice", "David", "Charlie", "Bob", "Alice"],
    "Product": ["Laptop", "Phone", "Chair", "Table", "Laptop", "Phone", "Chair", "Phone"],
    "Category": ["Electronics", "Electronics", "Furniture", "Furniture",
                 "Electronics", "Electronics", "Furniture", "Electronics"],
    "Quantity": [2, 1, 4, 1, 1, 2, 2, 1],
    "Price": [800, 500, 100, 250, 800, 500, 100, 500],
    "Total Sales": [1600, 500, 400, 250, 800, 1000, 200, 500]
}
df = pd.DataFrame(data)
df

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500

In [3]:
# 2. Add New Column (10% Discount)
df["Discount"] = df["Total Sales"] * 0.10
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

In [4]:
# 3. Add New Row
new_record = {
    "Order ID": 1009,
    "Customer": "Eve",
    "Product": "Tablet",
    "Category": "Electronics",
    "Quantity": 1,
    "Price": 300,
    "Total Sales": 300,
    "Discount": 30
}
df.loc[len(df)] = new_record
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Tablet,Electronics,1,300,300,30.0

In [5]:
# 4. Filter Electronics Category
electronics_df = df[df["Category"] == "Electronics"]
print(electronics_df)

   Order ID Customer Product     Category  Quantity  Price  Total Sales  \
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
7      1008    Alice   Phone  Electronics         1    500          500
8      1009      Eve  Tablet  Electronics         1    300          300

   Discount
0     160.0
1      50.0
4      80.0
5     100.0
7      50.0
8      30.0

In [6]:
# 5. Select Customer and Total Sales Columns
selected_columns = df[["Customer", "Total Sales"]]
print(selected_columns)

  Customer  Total Sales
0    Alice         1600
1      Bob          500
2  Charlie          400
3    Alice          250
4    David          800
5  Charlie         1000
6      Bob          200
7    Alice          500
8      Eve          300

In [7]:
# 6. Group by Customer and Calculate Total Sales
customer_sales = df.groupby("Customer")["Total Sales"].sum()
print(customer_sales)

Customer
Alice      2350
Bob         700
Charlie    1400
David       800
Eve         300
Name: Total Sales, dtype: int64

In [8]:
# 7. Sort by Total Sales Descending
sorted_df = df.sort_values(by="Total Sales", ascending=False)
print(sorted_df)

   Order ID Customer Product     Category  Quantity  Price  Total Sales  \
0      1001    Alice  Laptop  Electronics         2    800         1600
5      1006  Charlie   Phone  Electronics         2    500         1000
4      1005    David  Laptop  Electronics         1    800          800
7      1008    Alice   Phone  Electronics         1    500          500
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
8      1009      Eve  Tablet  Electronics         1    300          300
3      1004    Alice   Table    Furniture         1    250          250
6      1007      Bob   Chair    Furniture         2    100          200

   Discount
0     160.0
5     100.0
4      80.0
7      50.0
1      50.0
2      40.0
8      30.0
3      25.0
6      20.0

In [9]:
# 8. Apply Lambda Function
df["Sales Category"] = df["Total Sales"].apply(
    lambda x: "High" if x > 1000 else "Low"
)
print(df)

   Order ID Customer Product     Category  Quantity  Price  Total Sales  \
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500
8      1009      Eve  Tablet  Electronics         1    300          300

   Discount Sales Category
0     160.0           High
1      50.0            Low
2      40.0            Low
3      25.0            Low
4      80.0            Low
5     100.0            Low
6      20.0            Low
7      50.0            Low
8      30.0            Low

In [10]:
# 9. Save DataFrame as CSV
df.to_csv("sales_data.csv", index=False)
print("\nFile saved successfully as sales_data.csv")

File saved successfully as sales_data.csv