In [1]:
import pandas as pd
import numpy as np

In [3]:
arr = np.arange(1,21).reshape(4,5)
df = pd.DataFrame(arr)
df

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [4]:
data = {"roll_no":[101,102,103,104,105],"name":["Ajay","Sanjay","Nisha","Nidhi","Suraj"],"percentage":[78,89,56,71,77]}
df = pd.DataFrame(data)
df

   roll_no    name  percentage
0      101    Ajay          78
1      102  Sanjay          89
2      103   Nisha          56
3      104   Nidhi          71
4      105   Suraj          77

In [5]:
df['roll_no']

0    101
1    102
2    103
3    104
4    105
Name: roll_no, dtype: int64

In [6]:
df[['roll_no', 'name']]

   roll_no    name
0      101    Ajay
1      102  Sanjay
2      103   Nisha
3      104   Nidhi
4      105   Suraj

In [7]:
df.iloc[0]

roll_no        101
name          Ajay
percentage      78
Name: 0, dtype: object

In [9]:
df.iloc[[0,2,3]]

   roll_no   name  percentage
0      101   Ajay          78
2      103  Nisha          56
3      104  Nidhi          71

In [11]:
data = {"location":["Pune","Mumbai","Nagpur"]}
df_location = pd.DataFrame(data)
df_location

  location
0     Pune
1   Mumbai
2   Nagpur

In [13]:
df = pd.concat([df,df_location],axis=1)
df

   roll_no    name  percentage location location
0      101    Ajay          78     Pune     Pune
1      102  Sanjay          89   Mumbai   Mumbai
2      103   Nisha          56   Nagpur   Nagpur
3      104   Nidhi          71      NaN      NaN
4      105   Suraj          77      NaN      NaN

In [15]:
data = {"eid":[101,102,103,104],"ename":["Ajay","Vinay","Karan","Seema"],"salary":[14000,45000,36000,56000]}
df = pd.DataFrame(data,index = ['a','b','c','d'])
df

   eid  ename  salary
a  101   Ajay   14000
b  102  Vinay   45000
c  103  Karan   36000
d  104  Seema   56000

In [17]:
d = {"Location":["Pune","Mumbai","Chennai","Nagpur"]}
new_df = pd.DataFrame(d,index = ['a','b','c','d'])
new_df

  Location
a     Pune
b   Mumbai
c  Chennai
d   Nagpur

In [18]:
#Concatenate columnwise
pd.concat([df,new_df],axis=1)

   eid  ename  salary Location
a  101   Ajay   14000     Pune
b  102  Vinay   45000   Mumbai
c  103  Karan   36000  Chennai
d  104  Seema   56000   Nagpur

In [20]:
df["designation"] = ["Programmer","Manager","Tester","Manager"]
df

   eid  ename  salary designation
a  101   Ajay   14000  Programmer
b  102  Vinay   45000     Manager
c  103  Karan   36000      Tester
d  104  Seema   56000     Manager

In [21]:
df["designation"] = ["Programmer","Manager","Tester","Manager"]
df

   eid  ename  salary designation
a  101   Ajay   14000  Programmer
b  102  Vinay   45000     Manager
c  103  Karan   36000      Tester
d  104  Seema   56000     Manager

In [25]:
df.iloc[2] = [105,"Preeti",35000,"Programmer"]
df

   eid   ename  salary designation
a  101    Ajay   14000  Programmer
b  102   Vinay   45000     Manager
c  105  Preeti   35000  Programmer
d  104   Seema   56000     Manager

In [27]:
#add new row
df.loc['e'] = [105,"Preeti",35000,"Programmer"]
df

   eid   ename  salary designation
a  101    Ajay   14000  Programmer
b  102   Vinay   45000     Manager
c  105  Preeti   35000  Programmer
d  104   Seema   56000     Manager
e  105  Preeti   35000  Programmer

In [28]:
data = {"eid":[106,107,108,109],"ename":["Dinesh","Rohit","Teena","Kiran"],"salary":[14000,45000,36000,56000],
        'location':['Pune',"Pune","Mumbai","Mumbai"]}
df_1 = pd.DataFrame(data,index = ['f','g','h','i'])
df_1

   eid   ename  salary location
f  106  Dinesh   14000     Pune
g  107   Rohit   45000     Pune
h  108   Teena   36000   Mumbai
i  109   Kiran   56000   Mumbai

In [29]:
df_1["annual_salary"] = df_1["salary"]*12
df_1

   eid   ename  salary location  annual_salary
f  106  Dinesh   14000     Pune         168000
g  107   Rohit   45000     Pune         540000
h  108   Teena   36000   Mumbai         432000
i  109   Kiran   56000   Mumbai         672000

In [30]:
#Concatenate rowwise
df_combined = pd.concat([df,df_1],axis=0)
df_combined

   eid   ename  salary designation location  annual_salary
a  101    Ajay   14000  Programmer      NaN            NaN
b  102   Vinay   45000     Manager      NaN            NaN
c  105  Preeti   35000  Programmer      NaN            NaN
d  104   Seema   56000     Manager      NaN            NaN
e  105  Preeti   35000  Programmer      NaN            NaN
f  106  Dinesh   14000         NaN     Pune       168000.0
g  107   Rohit   45000         NaN     Pune       540000.0
h  108   Teena   36000         NaN   Mumbai       432000.0
i  109   Kiran   56000         NaN   Mumbai       672000.0

In [31]:
#To delete the row

#df_combined.drop('f',axis=0)
#df_combined.drop('f') #data is deleted and a new object is created, original is not modified
df_combined.drop('f',inplace=True) #row is deleted from existing object, new object is not created
df_combined

   eid   ename  salary designation location  annual_salary
a  101    Ajay   14000  Programmer      NaN            NaN
b  102   Vinay   45000     Manager      NaN            NaN
c  105  Preeti   35000  Programmer      NaN            NaN
d  104   Seema   56000     Manager      NaN            NaN
e  105  Preeti   35000  Programmer      NaN            NaN
g  107   Rohit   45000         NaN     Pune       540000.0
h  108   Teena   36000         NaN   Mumbai       432000.0
i  109   Kiran   56000         NaN   Mumbai       672000.0

In [32]:
#to delete column
df_combined.drop('location',axis=1)

   eid   ename  salary designation  annual_salary
a  101    Ajay   14000  Programmer            NaN
b  102   Vinay   45000     Manager            NaN
c  105  Preeti   35000  Programmer            NaN
d  104   Seema   56000     Manager            NaN
e  105  Preeti   35000  Programmer            NaN
g  107   Rohit   45000         NaN       540000.0
h  108   Teena   36000         NaN       432000.0
i  109   Kiran   56000         NaN       672000.0

In [33]:
df_combined

   eid   ename  salary designation location  annual_salary
a  101    Ajay   14000  Programmer      NaN            NaN
b  102   Vinay   45000     Manager      NaN            NaN
c  105  Preeti   35000  Programmer      NaN            NaN
d  104   Seema   56000     Manager      NaN            NaN
e  105  Preeti   35000  Programmer      NaN            NaN
g  107   Rohit   45000         NaN     Pune       540000.0
h  108   Teena   36000         NaN   Mumbai       432000.0
i  109   Kiran   56000         NaN   Mumbai       672000.0

In [34]:
df_combined.drop('location',axis=1,inplace=True)
df_combined

   eid   ename  salary designation  annual_salary
a  101    Ajay   14000  Programmer            NaN
b  102   Vinay   45000     Manager            NaN
c  105  Preeti   35000  Programmer            NaN
d  104   Seema   56000     Manager            NaN
e  105  Preeti   35000  Programmer            NaN
g  107   Rohit   45000         NaN       540000.0
h  108   Teena   36000         NaN       432000.0
i  109   Kiran   56000         NaN       672000.0

In [35]:
#modyfing existing strings
df_combined.loc['a',"location"]="Pune"
df_combined["location"] = "Pune"
df_combined

   eid   ename  salary designation  annual_salary location
a  101    Ajay   14000  Programmer            NaN     Pune
b  102   Vinay   45000     Manager            NaN     Pune
c  105  Preeti   35000  Programmer            NaN     Pune
d  104   Seema   56000     Manager            NaN     Pune
e  105  Preeti   35000  Programmer            NaN     Pune
g  107   Rohit   45000         NaN       540000.0     Pune
h  108   Teena   36000         NaN       432000.0     Pune
i  109   Kiran   56000         NaN       672000.0     Pune

In [36]:
df_combined.loc[['g','h','i'],"designation"]="Tester"
df_combined

   eid   ename  salary designation  annual_salary location
a  101    Ajay   14000  Programmer            NaN     Pune
b  102   Vinay   45000     Manager            NaN     Pune
c  105  Preeti   35000  Programmer            NaN     Pune
d  104   Seema   56000     Manager            NaN     Pune
e  105  Preeti   35000  Programmer            NaN     Pune
g  107   Rohit   45000      Tester       540000.0     Pune
h  108   Teena   36000      Tester       432000.0     Pune
i  109   Kiran   56000      Tester       672000.0     Pune

In [37]:
#Display top 5 records
df_combined.head()

   eid   ename  salary designation  annual_salary location
a  101    Ajay   14000  Programmer            NaN     Pune
b  102   Vinay   45000     Manager            NaN     Pune
c  105  Preeti   35000  Programmer            NaN     Pune
d  104   Seema   56000     Manager            NaN     Pune
e  105  Preeti   35000  Programmer            NaN     Pune

In [38]:
#Display top 3 records
df.head(3)

   eid   ename  salary designation
a  101    Ajay   14000  Programmer
b  102   Vinay   45000     Manager
c  105  Preeti   35000  Programmer

In [39]:
#Display last 5 records
df_combined.tail()

   eid   ename  salary designation  annual_salary location
d  104   Seema   56000     Manager            NaN     Pune
e  105  Preeti   35000  Programmer            NaN     Pune
g  107   Rohit   45000      Tester       540000.0     Pune
h  108   Teena   36000      Tester       432000.0     Pune
i  109   Kiran   56000      Tester       672000.0     Pune

In [40]:
df_combined.salary.mean()

np.float64(40250.0)

In [41]:
df_combined.salary.max()

56000

In [42]:
df_combined.salary.min()

14000

In [43]:
df_combined.salary.sum()

np.int64(322000)

In [44]:
df_combined.salary.std()

13646.035531035588

In [45]:
df_combined.salary.mode()

0    35000
1    45000
2    56000
Name: salary, dtype: int64

In [46]:
df_combined.salary.median()

40500.0

In [47]:
df_combined.salary.mean()

np.float64(40250.0)