In [1]:
import pandas as pd
import numpy as np

In [2]:
emp = pd.DataFrame({"empno":[101,102,103,104,105,106,107],
                   "Name":["Rupesh","Aadesh","Sanket","Pooja","Sonali","Priyanka","Tanuja"],
                   "Salary":[32000,25000,34000,45000,26000,35000,35000],
                  "deptno":["d101","d102","d101","d101","d103","d103","d102"]})
emp

   empno      Name  Salary deptno
0    101    Rupesh   32000   d101
1    102    Aadesh   25000   d102
2    103    Sanket   34000   d101
3    104     Pooja   45000   d101
4    105    Sonali   26000   d103
5    106  Priyanka   35000   d103
6    107    Tanuja   35000   d102

In [3]:
result = emp.groupby("deptno")

In [4]:
for x in result:
  print(x)

('d101',    empno    Name  Salary deptno
0    101  Rupesh   32000   d101
2    103  Sanket   34000   d101
3    104   Pooja   45000   d101)
('d102',    empno    Name  Salary deptno
1    102  Aadesh   25000   d102
6    107  Tanuja   35000   d102)
('d103',    empno      Name  Salary deptno
4    105    Sonali   26000   d103
5    106  Priyanka   35000   d103)

In [5]:
result.max()["Salary"]

deptno
d101    45000
d102    35000
d103    35000
Name: Salary, dtype: int64

In [6]:
emp.groupby("deptno").max()["Salary"]

deptno
d101    45000
d102    35000
d103    35000
Name: Salary, dtype: int64

In [7]:
emp = pd.DataFrame({"empno":[101,102,103,104,105,106,107,108,109,110,111,112],
                   "Name":["Rupesh","Aadesh","Sanket","Pooja","Sonali","Priyanka","Tanuja",
                          'Priti','Anuj','Pranav','Seema','Tanvi'],
                   "Salary":[32000,25000,34000,45000,26000,35000,35000,29000,27000,42000,32000,12000],
                  "dno":["d101","d102","d101",'d104',"d103",'d104',"d102","d101","d102",
                         "d103","d101",'d104']})

emp

    empno      Name  Salary   dno
0     101    Rupesh   32000  d101
1     102    Aadesh   25000  d102
2     103    Sanket   34000  d101
3     104     Pooja   45000  d104
4     105    Sonali   26000  d103
5     106  Priyanka   35000  d104
6     107    Tanuja   35000  d102
7     108     Priti   29000  d101
8     109      Anuj   27000  d102
9     110    Pranav   42000  d103
10    111     Seema   32000  d101
11    112     Tanvi   12000  d104

In [8]:
emp.sort_values('dno')

    empno      Name  Salary   dno
0     101    Rupesh   32000  d101
2     103    Sanket   34000  d101
7     108     Priti   29000  d101
10    111     Seema   32000  d101
1     102    Aadesh   25000  d102
6     107    Tanuja   35000  d102
8     109      Anuj   27000  d102
4     105    Sonali   26000  d103
9     110    Pranav   42000  d103
3     104     Pooja   45000  d104
5     106  Priyanka   35000  d104
11    112     Tanvi   12000  d104

In [9]:
result = emp.groupby(['dno'])
result

In [10]:
df_group = pd.DataFrame(result)
df_group

         0                                                  1
0  (d101,)      empno    Name  Salary   dno
0     101  Rup...
1  (d102,)     empno    Name  Salary   dno
1    102  Aades...
2  (d103,)     empno    Name  Salary   dno
4    105  Sonal...
3  (d104,)      empno      Name  Salary   dno
3     104   ...

In [12]:
result['empno'].count()

dno
d101    4
d102    3
d103    2
d104    3
Name: empno, dtype: int64

In [13]:
emp.groupby(['dno'])['Salary'].max()

dno
d101    34000
d102    35000
d103    42000
d104    45000
Name: Salary, dtype: int64

In [14]:
emp.groupby(['dno'])['Salary'].agg(['min','max','mean','sum'])

        min    max          mean     sum
dno
d101  29000  34000  31750.000000  127000
d102  25000  35000  29000.000000   87000
d103  26000  42000  34000.000000   68000
d104  12000  45000  30666.666667   92000