In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {"eid":[101,102,103,104],"ename":["Kiran","Khushbu","Suraj","Pradeep"],
        "basic":[23000,34000,45000,45000]}
df = pd.DataFrame(data)
df

   eid    ename  basic
0  101    Kiran  23000
1  102  Khushbu  34000
2  103    Suraj  45000
3  104  Pradeep  45000

In [3]:
df_new = pd.DataFrame(['Pune','Mumbai','Pune','Mumbai'])
df['location'] = df_new
df

   eid    ename  basic location
0  101    Kiran  23000     Pune
1  102  Khushbu  34000   Mumbai
2  103    Suraj  45000     Pune
3  104  Pradeep  45000   Mumbai

In [4]:
df_designation = pd.DataFrame(['Manager','Developer','Developer','Tester'],
                              index = np.arange(105,109))
df_designation

             0
105    Manager
106  Developer
107  Developer
108     Tester

In [5]:
df["Designation"] = df_designation
df

   eid    ename  basic location Designation
0  101    Kiran  23000     Pune         NaN
1  102  Khushbu  34000   Mumbai         NaN
2  103    Suraj  45000     Pune         NaN
3  104  Pradeep  45000   Mumbai         NaN

In [7]:
df_final = pd.concat([df,df_designation],axis=1)
df_final.isna()

       eid  ename  basic  location  Designation      0
0    False  False  False     False         True   True
1    False  False  False     False         True   True
2    False  False  False     False         True   True
3    False  False  False     False         True   True
105   True   True   True      True         True  False
106   True   True   True      True         True  False
107   True   True   True      True         True  False
108   True   True   True      True         True  False

In [8]:
#Find out total number of missing values in a specific column
df_final.isna().sum()

eid            4
ename          4
basic          4
location       4
Designation    8
0              4
dtype: int64

In [9]:
#Delete the missing values, row wise
df_final.dropna()

Empty DataFrame
Columns: [eid, ename, basic, location, Designation, 0]
Index: []

In [10]:
df_final.dropna(axis=1)
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune         NaN        NaN
1    102.0  Khushbu  34000.0   Mumbai         NaN        NaN
2    103.0    Suraj  45000.0     Pune         NaN        NaN
3    104.0  Pradeep  45000.0   Mumbai         NaN        NaN
105    NaN      NaN      NaN      NaN         NaN    Manager
106    NaN      NaN      NaN      NaN         NaN  Developer
107    NaN      NaN      NaN      NaN         NaN  Developer
108    NaN      NaN      NaN      NaN         NaN     Tester

In [11]:
df_final['Designation']  = df_final[0]
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune         NaN        NaN
1    102.0  Khushbu  34000.0   Mumbai         NaN        NaN
2    103.0    Suraj  45000.0     Pune         NaN        NaN
3    104.0  Pradeep  45000.0   Mumbai         NaN        NaN
105    NaN      NaN      NaN      NaN     Manager    Manager
106    NaN      NaN      NaN      NaN   Developer  Developer
107    NaN      NaN      NaN      NaN   Developer  Developer
108    NaN      NaN      NaN      NaN      Tester     Tester

In [12]:
df_final.drop(0,axis=1)

       eid    ename    basic location Designation
0    101.0    Kiran  23000.0     Pune         NaN
1    102.0  Khushbu  34000.0   Mumbai         NaN
2    103.0    Suraj  45000.0     Pune         NaN
3    104.0  Pradeep  45000.0   Mumbai         NaN
105    NaN      NaN      NaN      NaN     Manager
106    NaN      NaN      NaN      NaN   Developer
107    NaN      NaN      NaN      NaN   Developer
108    NaN      NaN      NaN      NaN      Tester

In [13]:
df_final['Designation'].mode() #Output here is a series object
#But we want string
x = df_final['Designation'].mode()[0]

In [14]:
df_final['Designation'].fillna(x) #Whenever you will see output it means original data is not changed, new object is created

0      Developer
1      Developer
2      Developer
3      Developer
105      Manager
106    Developer
107    Developer
108       Tester
Name: Designation, dtype: object

In [15]:
df_final['Designation'].fillna(x,inplace=True)

/tmp/ipykernel_5564/528817345.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['Designation'].fillna(x,inplace=True)

In [16]:
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune   Developer        NaN
1    102.0  Khushbu  34000.0   Mumbai   Developer        NaN
2    103.0    Suraj  45000.0     Pune   Developer        NaN
3    104.0  Pradeep  45000.0   Mumbai   Developer        NaN
105    NaN      NaN      NaN      NaN     Manager    Manager
106    NaN      NaN      NaN      NaN   Developer  Developer
107    NaN      NaN      NaN      NaN   Developer  Developer
108    NaN      NaN      NaN      NaN      Tester     Tester

In [17]:
sal = df_final['basic'].mean()
df_final['basic'].fillna(sal,inplace=True)

/tmp/ipykernel_5564/269373619.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['basic'].fillna(sal,inplace=True)

In [18]:
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune   Developer        NaN
1    102.0  Khushbu  34000.0   Mumbai   Developer        NaN
2    103.0    Suraj  45000.0     Pune   Developer        NaN
3    104.0  Pradeep  45000.0   Mumbai   Developer        NaN
105    NaN      NaN  36750.0      NaN     Manager    Manager
106    NaN      NaN  36750.0      NaN   Developer  Developer
107    NaN      NaN  36750.0      NaN   Developer  Developer
108    NaN      NaN  36750.0      NaN      Tester     Tester

In [19]:
df_final.ffill() #forward fill

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune   Developer        NaN
1    102.0  Khushbu  34000.0   Mumbai   Developer        NaN
2    103.0    Suraj  45000.0     Pune   Developer        NaN
3    104.0  Pradeep  45000.0   Mumbai   Developer        NaN
105  104.0  Pradeep  36750.0   Mumbai     Manager    Manager
106  104.0  Pradeep  36750.0   Mumbai   Developer  Developer
107  104.0  Pradeep  36750.0   Mumbai   Developer  Developer
108  104.0  Pradeep  36750.0   Mumbai      Tester     Tester

In [20]:
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune   Developer        NaN
1    102.0  Khushbu  34000.0   Mumbai   Developer        NaN
2    103.0    Suraj  45000.0     Pune   Developer        NaN
3    104.0  Pradeep  45000.0   Mumbai   Developer        NaN
105    NaN      NaN  36750.0      NaN     Manager    Manager
106    NaN      NaN  36750.0      NaN   Developer  Developer
107    NaN      NaN  36750.0      NaN   Developer  Developer
108    NaN      NaN  36750.0      NaN      Tester     Tester

In [21]:
df_final.ffill(inplace=True)
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune   Developer        NaN
1    102.0  Khushbu  34000.0   Mumbai   Developer        NaN
2    103.0    Suraj  45000.0     Pune   Developer        NaN
3    104.0  Pradeep  45000.0   Mumbai   Developer        NaN
105  104.0  Pradeep  36750.0   Mumbai     Manager    Manager
106  104.0  Pradeep  36750.0   Mumbai   Developer  Developer
107  104.0  Pradeep  36750.0   Mumbai   Developer  Developer
108  104.0  Pradeep  36750.0   Mumbai      Tester     Tester

In [22]:
df_final.bfill(inplace=True)
df_final

       eid    ename    basic location Designation          0
0    101.0    Kiran  23000.0     Pune   Developer    Manager
1    102.0  Khushbu  34000.0   Mumbai   Developer    Manager
2    103.0    Suraj  45000.0     Pune   Developer    Manager
3    104.0  Pradeep  45000.0   Mumbai   Developer    Manager
105  104.0  Pradeep  36750.0   Mumbai     Manager    Manager
106  104.0  Pradeep  36750.0   Mumbai   Developer  Developer
107  104.0  Pradeep  36750.0   Mumbai   Developer  Developer
108  104.0  Pradeep  36750.0   Mumbai      Tester     Tester