In [2]:
import numpy as np
import pandas as pd

In [3]:
dept = pd.DataFrame({"deptno":["d101","d102","d103","d104"],
                    "dname":["Accounts","Finance","Marketing","Sales"]})
dept

  deptno      dname
0   d101   Accounts
1   d102    Finance
2   d103  Marketing
3   d104      Sales

In [4]:
data = {"eid":[101,102,103,104,105,106,107,108],
        "ename":["Kiran","Khushbu","Suraj","Pradeep","Ritu","Rahul","Samay","Tanuja"],
        "basic":[23000,34000,45000,45000,36000,51000,56000,78000],
        "deptno":["d101","d101","d102","d102","d102","d103","d103",np.nan]}
df_emp = pd.DataFrame(data)
df_emp

   eid    ename  basic deptno
0  101    Kiran  23000   d101
1  102  Khushbu  34000   d101
2  103    Suraj  45000   d102
3  104  Pradeep  45000   d102
4  105     Ritu  36000   d102
5  106    Rahul  51000   d103
6  107    Samay  56000   d103
7  108   Tanuja  78000    NaN

In [5]:
pd.merge(df_emp,dept) #Equjoin or Natural Join

   eid    ename  basic deptno      dname
0  101    Kiran  23000   d101   Accounts
1  102  Khushbu  34000   d101   Accounts
2  103    Suraj  45000   d102    Finance
3  104  Pradeep  45000   d102    Finance
4  105     Ritu  36000   d102    Finance
5  106    Rahul  51000   d103  Marketing
6  107    Samay  56000   d103  Marketing

In [7]:
data = {"eid":[101,102,103,104,105,106,107,108],
        "ename":["Kiran","Khushbu","Suraj","Pradeep","Ritu","Rahul","Samay","Tanuja"],
        "basic":[23000,34000,45000,45000,36000,51000,56000,78000],
        "d_no":["d101","d101","d102","d102","d102","d103","d103",np.nan]}
df_emp = pd.DataFrame(data)
df_emp

   eid    ename  basic  d_no
0  101    Kiran  23000  d101
1  102  Khushbu  34000  d101
2  103    Suraj  45000  d102
3  104  Pradeep  45000  d102
4  105     Ritu  36000  d102
5  106    Rahul  51000  d103
6  107    Samay  56000  d103
7  108   Tanuja  78000   NaN

In [8]:
#equijoin
pd.merge(df_emp,dept,left_on="d_no",right_on="deptno") #Use this when column names are not name

   eid    ename  basic  d_no deptno      dname
0  101    Kiran  23000  d101   d101   Accounts
1  102  Khushbu  34000  d101   d101   Accounts
2  103    Suraj  45000  d102   d102    Finance
3  104  Pradeep  45000  d102   d102    Finance
4  105     Ritu  36000  d102   d102    Finance
5  106    Rahul  51000  d103   d103  Marketing
6  107    Samay  56000  d103   d103  Marketing

In [9]:
#left join
print(df_emp)
print(dept)

   eid    ename  basic  d_no
0  101    Kiran  23000  d101
1  102  Khushbu  34000  d101
2  103    Suraj  45000  d102
3  104  Pradeep  45000  d102
4  105     Ritu  36000  d102
5  106    Rahul  51000  d103
6  107    Samay  56000  d103
7  108   Tanuja  78000   NaN
  deptno      dname
0   d101   Accounts
1   d102    Finance
2   d103  Marketing
3   d104      Sales

In [14]:
#left outer join
pd.merge(df_emp, dept, how="left", left_on="d_no", right_on="deptno")

   eid    ename  basic  d_no deptno      dname
0  101    Kiran  23000  d101   d101   Accounts
1  102  Khushbu  34000  d101   d101   Accounts
2  103    Suraj  45000  d102   d102    Finance
3  104  Pradeep  45000  d102   d102    Finance
4  105     Ritu  36000  d102   d102    Finance
5  106    Rahul  51000  d103   d103  Marketing
6  107    Samay  56000  d103   d103  Marketing
7  108   Tanuja  78000   NaN    NaN        NaN

In [15]:
#right outer join
pd.merge(df_emp, dept, how="right", left_on="d_no", right_on="deptno")

     eid    ename    basic  d_no deptno      dname
0  101.0    Kiran  23000.0  d101   d101   Accounts
1  102.0  Khushbu  34000.0  d101   d101   Accounts
2  103.0    Suraj  45000.0  d102   d102    Finance
3  104.0  Pradeep  45000.0  d102   d102    Finance
4  105.0     Ritu  36000.0  d102   d102    Finance
5  106.0    Rahul  51000.0  d103   d103  Marketing
6  107.0    Samay  56000.0  d103   d103  Marketing
7    NaN      NaN      NaN   NaN   d104      Sales

In [17]:
#full outer join
pd.merge(df_emp, dept, how="outer", left_on="d_no", right_on="deptno")

     eid    ename    basic  d_no deptno      dname
0  101.0    Kiran  23000.0  d101   d101   Accounts
1  102.0  Khushbu  34000.0  d101   d101   Accounts
2  103.0    Suraj  45000.0  d102   d102    Finance
3  104.0  Pradeep  45000.0  d102   d102    Finance
4  105.0     Ritu  36000.0  d102   d102    Finance
5  106.0    Rahul  51000.0  d103   d103  Marketing
6  107.0    Samay  56000.0  d103   d103  Marketing
7    NaN      NaN      NaN   NaN   d104      Sales
8  108.0   Tanuja  78000.0   NaN    NaN        NaN